version: '3.7'
services:
  somanet-jenkins-slave-raspberrypi:
    command: java -jar /usr/share/jenkins/slave.jar -jnlpUrl http://88.130.158.28/computer/raspberrypi/slave-agent.jnlp -workDir "/home/jenkins"
    container_name: jenkins-slave-raspberrypi
    image: digupats/jenkins-slave:3.27-1-alpine
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "500m"
    privileged: true
    restart: always
    volumes:
      - jenkins-data:/home/jenkins
      - /dev:/dev
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  jenkins-data:
